import { createTopic } from '../shared';

export const vocabularyTopics = [
  createTopic({ id:'word-formation', title:'Word formation', category:'vocabulary', summary:'Prefixes and suffixes let one word family express people, actions, qualities and opposites.', keywords:['word formation','prefixes','suffixes'], focus:'Use sentence grammar to predict the required word class before changing the root.', correct:'Her explanation was clear and convincing.', wrong:'Her explain was clear and convinced.', question:'What noun comes from “reliable”?', choices:['reliability','reliableness','reliation'], answer:'reliability', gap:'The change was completely ___. (EXPECT)', gapAnswer:'unexpected', transform:'Use a noun: The system is efficient.', transformAnswer:'The system works with great efficiency.' }),
  createTopic({ id:'collocations', title:'Collocations that sound natural', category:'vocabulary', summary:'Fluent speech relies on predictable word partnerships such as highly unlikely, deeply concerned and raise awareness.', keywords:['collocations','adverbs','natural English'], focus:'Record vocabulary in chunks and notice strength: strong coffee but heavy rain.', correct:'The campaign raised awareness of the issue.', wrong:'The campaign lifted awareness of the issue.', question:'Which adjective collocates with “rain”?', choices:['heavy','strong','powerful'], answer:'heavy', gap:'The two ideas are closely ___.', gapAnswer:'related', transform:'Make this natural: It is very unlikely.', transformAnswer:'It is highly unlikely.' }),
  createTopic({ id:'confusing-words', title:'Commonly confused words', category:'vocabulary', summary:'Near-synonyms differ in grammar, register or viewpoint: job/work, say/tell, remember/remind and affect/effect.', keywords:['confusing words','near synonyms','accuracy'], focus:'Compare the grammar and typical context of near-synonyms rather than treating them as interchangeable.', correct:'Please remind me to send the invoice.', wrong:'Please remember me to send the invoice.', question:'Which word is usually a verb meaning influence?', choices:['affect','effect','impactful'], answer:'affect', gap:'Can you ___ me what happened?', gapAnswer:'tell', transform:'Correct: I said her the truth.', transformAnswer:'I told her the truth.' }),
  createTopic({ id:'work-education', title:'Work and education', category:'vocabulary', summary:'Discuss qualifications, responsibilities, development and workplace change with precise neutral vocabulary.', keywords:['work','education','career'], focus:'Distinguish role, task, career and qualification, and use formal collocations in professional contexts.', correct:'The course helped me develop transferable skills.', wrong:'The course helped me grow transportable skills.', question:'What is a skill useful across different jobs?', choices:['transferable skill','moving skill','general task'], answer:'transferable skill', gap:'She meets all the job ___.', gapAnswer:'requirements', transform:'Use formal vocabulary: He moved to a higher position.', transformAnswer:'He was promoted.' }),
  createTopic({ id:'travel-culture', title:'Travel and culture', category:'vocabulary', summary:'Move beyond basic holiday vocabulary to discuss responsible tourism, cultural expectations and memorable experiences.', keywords:['travel','culture','tourism'], focus:'Use precise distinctions such as journey, trip and travel, and avoid broad stereotypes when discussing culture.', correct:'The journey took six hours, but the scenery was spectacular.', wrong:'The travel took six hours, but the views were spectacularly.', question:'Which noun is countable and means one visit away from home?', choices:['trip','travel','tourism'], answer:'trip', gap:'Visitors should respect local ___.', gapAnswer:'customs', transform:'Make precise: Our travel to Lviv was memorable.', transformAnswer:'Our trip to Lviv was memorable.' }),
  createTopic({ id:'society-environment', title:'Society and the environment', category:'vocabulary', level:'B2', summary:'Discuss causes, consequences and possible responses to social and environmental change without relying on vague words.', keywords:['society','environment','issues'], focus:'Build topic vocabulary around relationships: pose a threat, tackle inequality, reduce emissions and conserve resources.', correct:'The policy aims to reduce carbon emissions.', wrong:'The policy aims to make carbon emissions smaller.', question:'Which verb collocates with “an issue” meaning deal with it?', choices:['tackle','hit','do'], answer:'tackle', gap:'The species is under serious ___.', gapAnswer:'threat', transform:'Use a formal collocation: We must deal with inequality.', transformAnswer:'We must tackle inequality.' }),
];

