export type ExampleContext = 'general' | 'software';

export const softwareTenseExamples: Record<string, string[]> = {
  'present-simple': ['Our CI pipeline runs after every push.', 'The API returns a 404 when the resource does not exist.'],
  'present-continuous': ['The team is migrating the service to a new region.', 'I am reviewing the pull request now.'],
  'present-perfect': ['We have deployed the fix to production.', 'The monitoring service has detected three failures today.'],
  'present-perfect-continuous': ['The service has been dropping requests since the release.', 'We have been investigating the memory leak all morning.'],
  'past-simple': ['The deployment failed during the maintenance window.', 'I opened the logs and found the exception.'],
  'past-continuous': ['I was reviewing the patch when the build failed.', 'The workers were processing requests when the database went offline.'],
  'past-perfect': ['The job had already timed out before the alert fired.', 'We rolled back because the release had broken authentication.'],
  'past-perfect-continuous': ['We had been monitoring the service for an hour when latency increased.', 'The test had been running for twenty minutes before it failed.'],
  'future-simple': ['I’ll open an issue for this bug.', 'The new index will probably improve query performance.'],
  'future-continuous': ['At noon, we will be migrating the production database.', 'Will you be using the staging environment this afternoon?'],
  'future-perfect': ['By Friday, we will have completed the API migration.', 'The pipeline will have finished before the release window opens.'],
  'future-perfect-continuous': ['By June, the team will have been maintaining this service for five years.', 'At noon, the load test will have been running for six hours.'],
};

export const softwareTenseComparisonExamples: Record<string, string[]> = {
  'present-simple-continuous': ['I maintain the payments service.', 'I am fixing a production incident this week.'],
  'past-present-perfect': ['We deployed version 2.1 last Friday.', 'We have deployed the security fix.'],
  'perfect-simple-continuous': ['I have resolved three review comments.', 'I have been reviewing this pull request all morning.'],
  narrative: ['The workers were processing messages…', '…when the queue stopped…', '…because a credential had expired.'],
  'future-choice': ['I’ll restart the worker.', 'The queue is going to overflow.', 'We are deploying at six.'],
  'future-continuous-perfect': ['At noon, we will be migrating the database.', 'By noon, we will have completed the migration.'],
};

export const softwareGuideExamples: Record<string, Record<string, string[]>> = {
  conditionals: {
    'zero-first': ['If the cache expires, the application queries the database.', 'If the build passes, we’ll deploy the release.'],
    second: ['If we had more time, we would refactor this module.'],
    third: ['If we had validated the input, the service would not have crashed.'],
    mixed: ['If we had chosen a simpler architecture, the system would be easier to maintain now.'],
    wishes: ['I wish the tests ran faster.', 'I wish we had documented that decision.'],
  },
  modals: {
    'deduction-now': ['The worker must be offline.', 'This change might introduce a race condition.', 'That response can’t be coming from the new API.'],
    'deduction-past': ['The token must have expired.', 'The deployment might have changed the configuration.'],
    obligation: ['You mustn’t commit production credentials.', 'You don’t have to restart the service after this change.'],
    advice: ['You should add an integration test.', 'We should have reviewed the migration plan.'],
  },
  articles: {
    'a-the-zero': ['We found a bug in the authentication service. The bug affects new accounts.', 'Software needs regular maintenance.'],
    countability: ['a few failing tests', 'a little technical debt', 'some useful information'],
    'few-little': ['We have few deployment options left.', 'We still have a few deployment options.'],
  },
  'verb-patterns': {
    ing: ['She admitted deleting the configuration file.', 'We considered moving the job to a separate worker.'],
    to: ['The team decided to roll back.', 'We managed to reproduce the bug.'],
    'meaning-change': ['I remembered reviewing the function.', 'I remembered to review the function.'],
  },
  passive: {
    passive: ['The request is validated before it reaches the handler.', 'The patch has been deployed to production.'],
    causative: ['We had the security team review the design.', 'I’m getting my development laptop repaired.'],
  },
  reported: {
    statements: ['Maya said that she had fixed the failing test.', 'The lead told us that the release was blocked.'],
    questions: ['She asked why the build had failed.', 'He asked whether the endpoint was ready.'],
    commands: ['The lead told me not to merge the patch.', 'She asked us to update the runbook.'],
  },
  'phrasal-verbs': {
    'put-off': ['We put the release off until Monday.', 'We put it off because the tests were unstable.'],
    'work-out': ['We need to work out why the worker is leaking memory.', 'I finally worked out the correct query.'],
    'look-after': ['The platform team looks after the deployment infrastructure.'],
    'turn-up': ['A new error turned up in the production logs.', 'Could you turn the alert volume up?'],
  },
  prepositions: {
    'verb-on': ['The release depends on the security review.', 'Please concentrate on the failing integration test.'],
    'verb-for': ['She applied for a backend engineering role.', 'He apologised for breaking the build.'],
    adjectives: ['The platform team is responsible for maintaining the cluster.', 'I’m interested in learning Rust.'],
  },
  collocations: {
    'adjective-noun': ['A traffic spike caused a serious performance problem.', 'The incident required a quick response.'],
    'verb-noun': ['We need to make a technical decision.', 'The service raises an error when validation fails.'],
    'adverb-adjective': ['The two incidents are closely related.', 'A complete rewrite is highly unlikely.'],
  },
  'confused-words': {
    'say-tell': ['The reviewer said that the function was too complex.', 'She told me the deployment had finished.'],
    'remember-remind': ['I remembered the release checklist.', 'Please remind me to rotate the token.'],
    'affect-effect': ['The change affects performance.', 'Its effect is visible in the latency chart.'],
    'job-work': ['She found a new engineering job.', 'I have a lot of debugging work today.'],
  },
  'word-formation': {
    'noun-suffixes': ['deploy → deployment', 'reliable → reliability', 'integrate → integration'],
    'adjective-suffixes': ['scale → scalable', 'effect → effective', 'environment → environmental'],
    prefixes: ['stable → unstable', 'possible → impossible', 'configure → misconfigure'],
  },
  'phrase-bank': {
    'formal-email': ['I am writing to request access to the staging environment.', 'I would be grateful if you could confirm the release window.'],
    argument: ['One reason is that the change would reduce database load.', 'This suggests that a gradual rollout would be safer.'],
    contrast: ['Although the patch is small, it changes critical code.', 'Despite the extra complexity, the design is easier to scale.'],
    discussion: ['I see your point, but I’m not sure this design handles retries.', 'What I mean is that we need more production data.'],
    comparison: ['While option A is faster, option B is easier to maintain.', 'Compared with REST, the event-driven design is more flexible.'],
  },
};

export const softwareVerbExamples: Record<string, string> = {
  be: 'The API has been unstable since the deployment.',
  become: 'The query became slower as the table grew.',
  begin: 'The production migration has begun.',
  break: 'The configuration change broke authentication.',
  bring: 'The new index brought latency below 100 milliseconds.',
  build: 'The team has built a reusable component library.',
  buy: 'The company bought a licence for the monitoring tool.',
  catch: 'The error handler caught the exception.',
  choose: 'We have chosen PostgreSQL for the new service.',
  come: 'The database came back online after the restart.',
  cost: 'The outage cost the team several hours.',
  cut: 'Caching has cut the response time in half.',
  do: 'We have done the security review.',
  draw: 'The architect drew a sequence diagram.',
  drink: 'The on-call engineer drank coffee during the incident.',
  drive: 'A traffic spike drove CPU usage above 90 percent.',
  eat: 'We ate lunch during the pair-programming session.',
  fall: 'The error rate has fallen since the rollback.',
  feel: 'The old interface felt slow and unpredictable.',
  find: 'We have found the source of the memory leak.',
  fly: 'The engineering lead flew to the developer conference.',
  forget: 'I had forgotten to update the environment variable.',
  get: 'The build has got much faster.',
  give: 'The profiler has given us useful evidence.',
  go: 'The new release has gone live.',
  grow: 'The audit table has grown to ten million rows.',
  have: 'We had a database incident last night.',
  hear: 'Have you heard about the new API limit?',
  keep: 'We kept the old endpoint for backward compatibility.',
  know: 'We have known about this limitation for months.',
  leave: 'The previous developer left a helpful comment.',
  lose: 'The worker has lost its database connection.',
  make: 'We made a decision during the architecture review.',
  mean: 'The timeout meant that the job had to run again.',
  meet: 'The service has met its reliability target.',
  pay: 'The team paid down some technical debt.',
  put: 'I put the reproduction steps in the issue.',
  read: 'I read the incident report this morning.',
  run: 'The test suite has run successfully.',
  say: 'The reviewer said the function was too complex.',
  see: 'I have seen this error in the production logs.',
  send: 'The monitoring service sent an alert.',
  sit: 'The pull request sat in review for two days.',
  speak: 'Have you spoken to the platform team?',
  spend: 'We spent two hours debugging the race condition.',
  stand: 'The old server stood idle after the migration.',
  take: 'The database migration has taken three hours.',
  teach: 'The senior engineer taught us how the scheduler works.',
  tell: 'The logs told us where the request had failed.',
  think: 'We thought about using an event-driven design.',
  understand: 'I have understood the main cause of the incident.',
  wear: 'The on-call engineer wore a headset during the call.',
  win: 'The simpler design has won the team’s support.',
  write: 'I have written a regression test for the bug.',
};
