export interface TenseReference {
  id: string;
  name: string;
  time: 'Present' | 'Past' | 'Future';
  form: string;
  use: string;
  signalWords: string[];
  examples: string[];
  negative: string;
  question: string;
  viewpoint: string;
  contrast: string;
  mistake: { wrong:string; right:string };
}

export const tenseReferences: TenseReference[] = [
  { id:'present-simple', name:'Present simple', time:'Present', form:'subject + base verb / verb-s', use:'Routines, repeated actions, facts and permanent situations.', signalWords:['usually','every day','often'], examples:['I walk to work most days.','The library closes at six.'],negative:'subject + do/does not + base verb',question:'Do/Does + subject + base verb?',viewpoint:'A fact, habit or complete repeated event.',contrast:'Present continuous for temporary or changing situations.',mistake:{wrong:'She work from home every day.',right:'She works from home every day.'} },
  { id:'present-continuous', name:'Present continuous', time:'Present', form:'subject + am/is/are + verb-ing', use:'Actions happening now, temporary situations and changing trends.', signalWords:['now','at the moment','this week'], examples:['She is talking to a client now.','More people are working from home.'],negative:'subject + am/is/are not + verb-ing',question:'Am/Is/Are + subject + verb-ing?',viewpoint:'An activity seen in progress or around now.',contrast:'Present simple for routines and permanent facts.',mistake:{wrong:'I am knowing the answer.',right:'I know the answer.'} },
  { id:'present-perfect', name:'Present perfect', time:'Present', form:'subject + have/has + past participle', use:'Past actions connected to now, life experience and unfinished time periods.', signalWords:['already','yet','ever','since'], examples:['I have finished the report.','Have you ever visited Edinburgh?'],negative:'subject + have/has not + past participle',question:'Have/Has + subject + past participle?',viewpoint:'Earlier event viewed through its relevance now.',contrast:'Past simple when the time is finished and stated.',mistake:{wrong:'I have seen her yesterday.',right:'I saw her yesterday.'} },
  { id:'present-perfect-continuous', name:'Present perfect continuous', time:'Present', form:'subject + have/has been + verb-ing', use:'An activity continuing until now or a recent activity with a visible result.', signalWords:['for','since','all morning'], examples:['We have been waiting for an hour.','It has been raining, so the streets are wet.'],negative:'subject + have/has not been + verb-ing',question:'Have/Has + subject + been + verb-ing?',viewpoint:'Duration or repeated activity continuing toward now.',contrast:'Present perfect simple for completion, quantity or a state.',mistake:{wrong:'I have been knowing her for years.',right:'I have known her for years.'} },
  { id:'past-simple', name:'Past simple', time:'Past', form:'subject + past form', use:'Completed actions and sequences at a finished time in the past.', signalWords:['yesterday','last week','in 2024'], examples:['They moved here last year.','I opened the door and switched on the light.'],negative:'subject + did not + base verb',question:'Did + subject + base verb?',viewpoint:'A completed event inside a finished past time.',contrast:'Present perfect when the past remains connected to now.',mistake:{wrong:'Did you went home?',right:'Did you go home?'} },
  { id:'past-continuous', name:'Past continuous', time:'Past', form:'subject + was/were + verb-ing', use:'An action in progress at a past moment, often the background to another event.', signalWords:['while','at five o’clock','when'], examples:['I was cooking when you called.','At eight, they were still travelling.'],negative:'subject + was/were not + verb-ing',question:'Was/Were + subject + verb-ing?',viewpoint:'An activity open and in progress at a past point.',contrast:'Past simple for the event that interrupts or advances a story.',mistake:{wrong:'I cooked when you called.',right:'I was cooking when you called.'} },
  { id:'past-perfect', name:'Past perfect', time:'Past', form:'subject + had + past participle', use:'An action completed before another past action or point.', signalWords:['before','after','by the time'], examples:['The train had left before we arrived.','She was nervous because she had not flown before.'],negative:'subject + had not + past participle',question:'Had + subject + past participle?',viewpoint:'A completed event viewed from a later past point.',contrast:'Past simple for the main sequence of past events.',mistake:{wrong:'When we arrived, the train already left.',right:'When we arrived, the train had already left.'} },
  { id:'past-perfect-continuous', name:'Past perfect continuous', time:'Past', form:'subject + had been + verb-ing', use:'The duration or cause of an activity continuing up to a past point.', signalWords:['for','since','before'], examples:['They had been driving for hours when they stopped.','He was tired because he had been studying.'],negative:'subject + had not been + verb-ing',question:'Had + subject + been + verb-ing?',viewpoint:'Duration or cause continuing toward a past point.',contrast:'Past perfect simple for completion or result.',mistake:{wrong:'He was tired because he studied all night.',right:'He was tired because he had been studying all night.'} },
  { id:'future-simple', name:'Future simple', time:'Future', form:'subject + will + base verb', use:'Predictions, spontaneous decisions, promises and offers.', signalWords:['probably','I think','tomorrow'], examples:['I think the plan will work.','I’ll carry that bag for you.'],negative:'subject + will not + base verb',question:'Will + subject + base verb?',viewpoint:'A prediction or decision made from the present moment.',contrast:'Going to for prior intentions/evidence; present continuous for arrangements.',mistake:{wrong:'I will meeting her at six; it is arranged.',right:'I am meeting her at six.'} },
  { id:'future-continuous', name:'Future continuous', time:'Future', form:'subject + will be + verb-ing', use:'An action that will be in progress at a specific future time.', signalWords:['this time tomorrow','at noon'], examples:['This time tomorrow, we will be flying to Rome.','Will you be using the car tonight?'],negative:'subject + will not be + verb-ing',question:'Will + subject + be + verb-ing?',viewpoint:'An activity viewed in progress at a future point.',contrast:'Future simple for a decision; future perfect for completion.',mistake:{wrong:'This time tomorrow, we will fly over France.',right:'This time tomorrow, we will be flying over France.'} },
  { id:'future-perfect', name:'Future perfect', time:'Future', form:'subject + will have + past participle', use:'An action that will be complete before a future point.', signalWords:['by','by the time','before'], examples:['By Friday, I will have completed the course.','They will have left before we get there.'],negative:'subject + will not have + past participle',question:'Will + subject + have + past participle?',viewpoint:'A completed result viewed from a later future point.',contrast:'Future continuous for an activity still in progress.',mistake:{wrong:'By Friday, I will complete the course.',right:'By Friday, I will have completed the course.'} },
  { id:'future-perfect-continuous', name:'Future perfect continuous', time:'Future', form:'subject + will have been + verb-ing', use:'The duration of an activity continuing up to a future point.', signalWords:['for','by','by the time'], examples:['In June, she will have been teaching here for ten years.','By noon, we will have been travelling for six hours.'],negative:'subject + will not have been + verb-ing',question:'Will + subject + have been + verb-ing?',viewpoint:'Duration continuing toward a future measuring point.',contrast:'Future perfect simple for completed quantity or result.',mistake:{wrong:'In June, she will teach here for ten years.',right:'In June, she will have been teaching here for ten years.'} },
];

export interface TenseComparison { id:string; title:string; situation:string; choices:{name:string;example:string;meaning:string}[]; question:string; answer:string }
export const tenseComparisons:TenseComparison[]=[
  {id:'present-simple-continuous',title:'Present simple vs continuous',situation:'Choose routine or temporary activity.',choices:[{name:'Present simple',example:'I work from home.',meaning:'This is my normal situation.'},{name:'Present continuous',example:'I am working from home this week.',meaning:'This is temporary.'}],question:'She normally drives, but today she ___ the bus.',answer:'is taking'},
  {id:'past-present-perfect',title:'Past simple vs present perfect',situation:'Choose a finished past time or a present connection.',choices:[{name:'Past simple',example:'I saw that film last Friday.',meaning:'The time is finished and stated.'},{name:'Present perfect',example:'I have seen that film.',meaning:'The experience matters now; no finished time is given.'}],question:'I ___ Maya yesterday.',answer:'saw'},
  {id:'perfect-simple-continuous',title:'Present perfect simple vs continuous',situation:'Choose result/quantity or activity/duration.',choices:[{name:'Present perfect',example:'I have written three pages.',meaning:'Focus on the completed quantity.'},{name:'Present perfect continuous',example:'I have been writing all morning.',meaning:'Focus on the activity and duration.'}],question:'The ground is wet because it ___.',answer:'has been raining'},
  {id:'narrative',title:'Past simple, continuous and perfect',situation:'Place events within a story.',choices:[{name:'Past continuous',example:'I was walking home…',meaning:'Background already in progress.'},{name:'Past simple',example:'…when I realised…',meaning:'Main event advances the story.'},{name:'Past perfect',example:'…I had left my keys at work.',meaning:'Earlier event before the story point.'}],question:'By the time we arrived, the concert ___.',answer:'had started'},
  {id:'future-choice',title:'Will, going to and present continuous',situation:'Choose by evidence and commitment, not simply future time.',choices:[{name:'will',example:'I’ll answer the phone.',meaning:'Decision made now.'},{name:'going to',example:'It is going to rain.',meaning:'Prediction from visible evidence or prior intention.'},{name:'present continuous',example:'I am meeting Ana at six.',meaning:'Personal arrangement.'}],question:'Look at those clouds! It ___.',answer:'is going to rain'},
  {id:'future-continuous-perfect',title:'Future continuous vs perfect',situation:'View an activity in progress or already complete at a future point.',choices:[{name:'Future continuous',example:'At noon, I will be travelling.',meaning:'In progress at noon.'},{name:'Future perfect',example:'By noon, I will have arrived.',meaning:'Complete before noon.'}],question:'By Friday, we ___ the project.',answer:'will have completed'}
];
