import { createTopic } from '../shared';

export const verbTopics = [
  createTopic({ id:'irregular-verbs', title:'Irregular verbs master table', category:'verbs', summary:'High-frequency irregular verbs become easier when grouped by sound and spelling pattern rather than memorised as one long list.', keywords:['irregular verbs','past participle','reference'], focus:'Learn base, past and participle together, then retrieve each form inside a meaningful sentence.', correct:'She has written three reports this week.', wrong:'She has wrote three reports this week.', question:'What is the past participle of write?', choices:['written','wrote','writed'], answer:'written', gap:'They have ___ the final decision.', gapAnswer:'made', transform:'Use the present perfect: He took the wrong train.', transformAnswer:'He has taken the wrong train.', table:{headers:['Base','Past','Participle'],rows:[['write','wrote','written'],['take','took','taken'],['choose','chose','chosen'],['bring','brought','brought']]} }),
  createTopic({ id:'phrasal-verbs', title:'Core phrasal verbs', category:'verbs', summary:'Phrasal verbs carry precise meanings and differ in whether their object can split the verb from its particle.', keywords:['phrasal verbs','particles','separable'], focus:'Learn the whole phrase with its grammar and a realistic collocation, not the verb and particle separately.', correct:'We had to put the meeting off until Friday.', wrong:'We had to put off it until Friday.', question:'Which phrasal verb means postpone?', choices:['put off','turn up','work out'], answer:'put off', gap:'I finally ___ out why the printer was not working.', gapAnswer:'worked', transform:'Replace “cancelled”: They cancelled the match.', transformAnswer:'They called off the match.' }),
  createTopic({ id:'dependent-prepositions', title:'Dependent prepositions', category:'verbs', summary:'Many verbs and adjectives select a fixed preposition; the combination often cannot be predicted from another language.', keywords:['prepositions','verb patterns','adjectives'], focus:'Store the headword and preposition as one chunk: depend on, responsible for, interested in.', correct:'She apologised to us for arriving late.', wrong:'She apologised us about arriving late.', question:'Which preposition follows succeed?', choices:['in','at','on'], answer:'in', gap:'The result depends ___ several factors.', gapAnswer:'on', transform:'Correct: He insisted to paying for dinner.', transformAnswer:'He insisted on paying for dinner.' }),
  createTopic({ id:'verb-combinations', title:'Verb patterns and combinations', category:'verbs', summary:'Common combinations with make, do, take and get are a major source of naturalness at B2.', keywords:['verb patterns','collocations','make do take get'], focus:'Choose the verb as part of a conventional word partnership rather than from its dictionary meaning alone.', correct:'We need to make a decision by noon.', wrong:'We need to do a decision by noon.', question:'Which verb collocates with responsibility?', choices:['take','make','do'], answer:'take', gap:'Could you ___ me a favour?', gapAnswer:'do', transform:'Use a natural collocation: We must decide today.', transformAnswer:'We must make a decision today.' }),
];

