export interface IrregularVerb { base:string; past:string; participle:string; pronunciation:string; example:string; note:string }
const v=(base:string,past:string,participle:string,pronunciation:string,example:string,note='Do not add -ed.')=>({base,past,participle,pronunciation,example,note});
export const irregularVerbs:IrregularVerb[]=[
v('be','was / were','been','/biː/ – /wɒz, wɜː/ – /bɪn/','I have been there twice.','Use was with I/he/she/it and were with you/we/they.'),
v('become','became','become','/bɪˈkʌm/ – /bɪˈkeɪm/ – /bɪˈkʌm/','The area has become quieter.'),
v('begin','began','begun','/bɪˈɡɪn/ – /bɪˈɡæn/ – /bɪˈɡʌn/','The meeting has begun.'),
v('break','broke','broken','/breɪk/ – /brəʊk/ – /ˈbrəʊkən/','Someone has broken the window.'),
v('bring','brought','brought','/brɪŋ/ – /brɔːt/ – /brɔːt/','She brought her notes.'),
v('build','built','built','/bɪld/ – /bɪlt/ – /bɪlt/','They have built a new bridge.'),
v('buy','bought','bought','/baɪ/ – /bɔːt/ – /bɔːt/','I bought it yesterday.'),
v('catch','caught','caught','/kætʃ/ – /kɔːt/ – /kɔːt/','We caught the last train.'),
v('choose','chose','chosen','/tʃuːz/ – /tʃəʊz/ – /ˈtʃəʊzən/','Have you chosen a topic?'),
v('come','came','come','/kʌm/ – /keɪm/ – /kʌm/','They have come a long way.'),
v('cost','cost','cost','/kɒst/ – /kɒst/ – /kɒst/','The repair cost too much.','All three forms are identical.'),
v('cut','cut','cut','/kʌt/ – /kʌt/ – /kʌt/','I have cut the paper.','All three forms are identical.'),
v('do','did','done','/duː/ – /dɪd/ – /dʌn/','We have done enough.'),
v('draw','drew','drawn','/drɔː/ – /druː/ – /drɔːn/','She drew a quick map.'),
v('drink','drank','drunk','/drɪŋk/ – /dræŋk/ – /drʌŋk/','He has drunk all the water.'),
v('drive','drove','driven','/draɪv/ – /drəʊv/ – /ˈdrɪvən/','I have never driven abroad.'),
v('eat','ate','eaten','/iːt/ – /eɪt/ – /ˈiːtən/','Have you eaten yet?'),
v('fall','fell','fallen','/fɔːl/ – /fel/ – /ˈfɔːlən/','Prices have fallen.'),
v('feel','felt','felt','/fiːl/ – /felt/ – /felt/','I felt much better.'),
v('find','found','found','/faɪnd/ – /faʊnd/ – /faʊnd/','We have found a solution.'),
v('fly','flew','flown','/flaɪ/ – /fluː/ – /fləʊn/','She has flown to Rome.'),
v('forget','forgot','forgotten','/fəˈɡet/ – /fəˈɡɒt/ – /fəˈɡɒtən/','I had forgotten the address.'),
v('get','got','got / gotten','/ɡet/ – /ɡɒt/ – /ɡɒt/','Things have got easier.','Gotten is mainly American English.'),
v('give','gave','given','/ɡɪv/ – /ɡeɪv/ – /ˈɡɪvən/','They have given us more time.'),
v('go','went','gone','/ɡəʊ/ – /went/ – /ɡɒn/','Maya has gone home.'),
v('grow','grew','grown','/ɡrəʊ/ – /ɡruː/ – /ɡrəʊn/','The company has grown quickly.'),
v('have','had','had','/hæv/ – /hæd/ – /hæd/','We had a great time.'),
v('hear','heard','heard','/hɪə/ – /hɜːd/ – /hɜːd/','Have you heard the news?'),
v('keep','kept','kept','/kiːp/ – /kept/ – /kept/','She kept her promise.'),
v('know','knew','known','/nəʊ/ – /njuː/ – /nəʊn/','I have known him for years.'),
v('leave','left','left','/liːv/ – /left/ – /left/','They left at noon.'),
v('lose','lost','lost','/luːz/ – /lɒst/ – /lɒst/','I have lost my keys.'),
v('make','made','made','/meɪk/ – /meɪd/ – /meɪd/','We made a decision.'),
v('mean','meant','meant','/miːn/ – /ment/ – /ment/','What did you mean?'),
v('meet','met','met','/miːt/ – /met/ – /met/','We first met at university.'),
v('pay','paid','paid','/peɪ/ – /peɪd/ – /peɪd/','Have you paid the bill?'),
v('put','put','put','/pʊt/ – /pʊt/ – /pʊt/','I put it on the desk.','All three forms are identical.'),
v('read','read','read','/riːd/ – /red/ – /red/','I read it last night.','The spelling stays the same but the pronunciation changes.'),
v('run','ran','run','/rʌn/ – /ræn/ – /rʌn/','She has run three marathons.'),
v('say','said','said','/seɪ/ – /sed/ – /sed/','He said it was urgent.'),
v('see','saw','seen','/siː/ – /sɔː/ – /siːn/','I have seen that film.'),
v('send','sent','sent','/send/ – /sent/ – /sent/','I sent the email yesterday.'),
v('sit','sat','sat','/sɪt/ – /sæt/ – /sæt/','We sat near the window.'),
v('speak','spoke','spoken','/spiːk/ – /spəʊk/ – /ˈspəʊkən/','Have you spoken to Alex?'),
v('spend','spent','spent','/spend/ – /spent/ – /spent/','We spent too much time there.'),
v('stand','stood','stood','/stænd/ – /stʊd/ – /stʊd/','He stood by the door.'),
v('take','took','taken','/teɪk/ – /tʊk/ – /ˈteɪkən/','Someone has taken my seat.'),
v('teach','taught','taught','/tiːtʃ/ – /tɔːt/ – /tɔːt/','She taught English for years.'),
v('tell','told','told','/tel/ – /təʊld/ – /təʊld/','I told him the truth.'),
v('think','thought','thought','/θɪŋk/ – /θɔːt/ – /θɔːt/','I thought about your idea.'),
v('understand','understood','understood','/ˌʌndəˈstænd/ – /ˌʌndəˈstʊd/','I have understood the main point.'),
v('wear','wore','worn','/weə/ – /wɔː/ – /wɔːn/','He wore a dark suit.'),
v('win','won','won','/wɪn/ – /wʌn/ – /wʌn/','Our team has won.'),
v('write','wrote','written','/raɪt/ – /rəʊt/ – /ˈrɪtən/','I have written a reply.'),
];

